from enum import Enum, IntEnum


class BoardIdsEnum(IntEnum):
    CYTON_DAISY = 2


class StreamNumeric(IntEnum):
    CHUNK_SIZE = 16
    CHUNK_QUEUE_MAXSIZE = 256
    RAW_QUEUE_MAXSIZE = 256
    ACQUISITION_POLL_MS = 20
    GUI_REFRESH_MS = 30
    GUI_WINDOW_SECONDS = 6
    GUI_PROCESSING_BUFFER_SECONDS = 22
    GUI_FILTER_GUARD_SECONDS = 2
    SPECTRAL_REFRESH_MS = 40
    FFT_N = 256
    HEAD_INTENSITY_WINDOW_SECONDS = 1
    HEADMAP_GRID_SIZE = 96
    HEAD_CONTOUR_LEVELS = 12
    HEADMAP_DECIMATION = 4


class StreamFloat(float, Enum):
    BANDPASS_LOW_HZ = 4.0
    BANDPASS_HIGH_HZ = 40.0
    NOTCH_HZ = 60.0
    BAND_DELTA_LOW_HZ = 1.0
    BAND_DELTA_HIGH_HZ = 4.0
    BAND_THETA_LOW_HZ = 4.0
    BAND_THETA_HIGH_HZ = 8.0
    BAND_ALPHA_LOW_HZ = 8.0
    BAND_ALPHA_HIGH_HZ = 13.0
    BAND_BETA_LOW_HZ = 13.0
    BAND_BETA_HIGH_HZ = 30.0
    BAND_GAMMA_LOW_HZ = 30.0
    BAND_GAMMA_HIGH_HZ = 55.0
    BAND_POWER_EPS = 1e-12
    FFT_SMOOTHING_ALPHA = 0.9
    FFT_MIN_AMPLITUDE_UV = 0.01
    FFT_DISPLAY_Y_MAX_UV = 100.0
    HEAD_INTENSITY_MAX_UV = 200.0
    HEAD_INTENSITY_MIN_UV = 5.0
    HEADMAP_SMOOTHING_ALPHA = 0.9
    ELECTRODE_REL_DIAM = 0.12
    MONTAGE_LAYOUT_SCALE = 2.0


class StreamState(str, Enum):
    DISCONNECTED = "disconnected"
    CONNECTED = "connected"
    STREAMING = "streaming"
    ERROR = "error"
